void print_line(int number_of_lines, char *position, char *title);
void count_lines();
void put_input();
void count_chars();
void count_formats();
void split_whitspace(char *word);
void make_splicit_invisible_chars(char *str);
int wc();
int word_per_ln();
void occurrency_counter();
void histogram_length();
int histogram_dif_chars();
int power(int base, int y);
int power_exercise();
int degree_calc();
int longest_line();
